fix bug

diff --git a/xvideos-dl b/xvideos-dl
--- a/xvideos-dl
+++ b/xvideos-dl
@@ -31,16 +31,26 @@ find_unique_filename()
     eval "$UNIQUE_FILENAME_VAR=$FILENAME"
 }
 
-purge_temp()
+cleanup()
 {
-    if [ $# -ne 1 ]; then
-        echo "Fail! -- Expecting 1 argument! ==> $@"
+    if [ $# -ne 3 ]; then
+        echo "Fail! -- Expecting 3 argument! ==> $@"
         return 1 # non-zero as false
     fi
-    local TEMP=$1
-    if [ -f $TEMP ]; then
-        echo  "Safely removing temp file ==> $TEMP"
-        rm -f $TEMP
+    local PLACEHOLDER_TEMP=$1
+    local PARTIAL_TEMP=$2
+    local DONE_VAR=$3
+    local DONE_VALUE=0
+    eval "DONE_VALUE=\$$DONE_VAR"
+    if [ $DONE_VALUE -eq 0 ]; then
+        if [ -f $PLACEHOLDER_TEMP ]; then
+            echo  "Safely removing placeholder temp file ==> $PLACEHOLDER_TEMP"
+            rm -f $PLACEHOLDER_TEMP
+        fi
+    fi
+    if [ -f $PARTIAL_TEMP ]; then
+        echo  "Safely removing partial temp file ==> $PARTIAL_TEMP"
+        rm -f $PARTIAL_TEMP
     fi
 }
 
@@ -91,9 +101,11 @@ else
 fi
 touch $LOCAL_FILE
 TEMP=${LOCAL_FILE}.part
-trap "purge_temp $LOCAL_FILE; purge_temp $TEMP" EXIT
+trap "cleanup $LOCAL_FILE $TEMP DONE" EXIT
+DONE=0
 curl $EXTRACTED_URL > $TEMP
 mv $TEMP $LOCAL_FILE
+DONE=1
 
 echo ""
 echo "Download complete! ==> $LOCAL_FILE"
