waypoint ckin

diff --git a/xvideos-dl b/xvideos-dl
--- a/xvideos-dl
+++ b/xvideos-dl
@@ -4,32 +4,45 @@ CMD=`basename $0`
 
 show_help()
 {
-    echo "Usage: $CMD <URL>"
+    echo "Usage: $CMD <URL> [FORCE={0/1}]"
 }
 
 find_unique_filename()
 {
-    UNIQUE_FILENAME_VAR=$1
-    FILENAME=$2
+    if [ $# -ne 2 ]; then
+        echo "Fail! -- Expecting 2 arguments! ==> $@"
+        return 1 # non-zero as false
+    fi
+    local UNIQUE_FILENAME_VAR=$1
+    local FILENAME=$2
     if [ -f $FILENAME ]; then
         COUNTER=0
         while [ -f $FILENAME ]; do
-            echo "File exists! ==> `basename $FILENAME`"
-            FILENAME=`echo $FILENAME | sed "s#[0-9]\+\.#$COUNTER\.#g"`
+            echo "File exists: `basename $FILENAME`"
+            local NEW_FILENAME=`echo $FILENAME | sed "s#\(.*\)-[0-9]\+\.#\1-$COUNTER\.#g"`
+            if [ "$NEW_FILENAME" == "$FILENAME" ]; then
+                NEW_FILENAME=`echo $FILENAME | sed "s#\(.*\)\.#\1-$COUNTER\.#g"`
+            fi
+            FILENAME=$NEW_FILENAME
             COUNTER=$(( $COUNTER + 1 ))
         done
-        echo "Saving as.. ==> `basename $FILENAME`"
+        echo "Next unique filename: `basename $FILENAME`"
     fi
-    $UNIQUE_FILENAME_VAR=$FILENAME
+    eval "$UNIQUE_FILENAME_VAR=$FILENAME"
 }
 
-if [ $# -ne 1 ]; then
-    echo "fail! -- expect 1 arguments! ==> $@"
+if [ $# -ne 1 -a $# -ne 2 ]; then
+    echo "Fail! -- Expecting 1 or 2 arguments! ==> $@"
     show_help
     exit 1
 fi
 
 URL=$1
+FORCE=$2
+
+if [ -z "$FORCE" ]; then
+    FORCE=0
+fi
 
 echo ""
 echo "Extracting video URL from.. ==> $URL"
@@ -50,9 +63,19 @@ EXTRACTED_URL=`curl $URL       | # download HTML using curl
         sed 's#\%26#\&#g'`       # replace %26 --> &
 
 echo ""
-echo "Downloading video from.. ==> $EXTRACTED_URL"
+echo "Downloading from.. ==> $EXTRACTED_URL"
 LOCAL_FILE="`pwd`/`basename $URL`.flv"
-find_unique_filename LOCAL_FILE $LOCAL_FILE
+LOCAL_FILE=`echo $LOCAL_FILE | sed "s/ /_/g"`
+if [ $FORCE -eq 1 ] && [ -f $LOCAL_FILE ]; then
+    echo "Overwriting.. ==> `basename $LOCAL_FILE`"
+else
+    if find_unique_filename LOCAL_FILE $LOCAL_FILE; then
+        : # do nothing
+    else
+        exit 1
+    fi
+    echo "Saving as new.. ==> `basename $LOCAL_FILE`"
+fi
 curl $EXTRACTED_URL > $LOCAL_FILE
 
 echo ""
